#!/bin/bash

TGT_BUILD_IMAGE_EXPECT_LIST="$(ls -l $HOME/script-env | grep -P '^d' | awk '{print $9}' | grep -v docker-build-log)"
TGT_BUILD_IMAGE_EXPECT_CNT=$(echo "$TGT_BUILD_IMAGE_EXPECT_LIST" | wc -l )

TGT_BUILD_IMAGE_ACTUAL_LIST="$(docker images | awk '{print $1}' | grep -P '(?:-[0-9]){1,}' | xargs -I@ bash -c "echo @ && docker history --human=false @ | sort -rk2 | sed -r 's;\s{1,}; ;g;' | cut -d' ' -f2 | sed -n '2p'" | xargs -n2)"
TGT_BUILD_IMAGE_ACTUAL_SUMMARY_LIST="$( echo "$TGT_BUILD_IMAGE_ACTUAL_LIST" | cut -d' ' -f1)"
TGT_BUILD_IMAGE_ACTUAL_DETAILE_LIST="$TGT_BUILD_IMAGE_ACTUAL_LIST"
TGT_BUILD_IMAGE_ACTUAL_CNT=$(echo "$TGT_BUILD_IMAGE_ACTUAL_DETAILE_LIST" | wc -l)

TGT_BUILD_IMAGE_ACTUAL_TODAY_DONE_LIST="$(echo "$TGT_BUILD_IMAGE_ACTUAL_DETAILE_LIST" | grep "$(date "+%Y-%m-%d")")"
TGT_BUILD_IMAGE_ACTUAL_SUMMARY_TODAY_DONE_LIST="$(echo "$TGT_BUILD_IMAGE_ACTUAL_TODAY_DONE_LIST" | cut -d' ' -f1)"
TGT_BUILD_IMAGE_ACTUAL_DETAILE_TODAY_DONE_LIST="$TGT_BUILD_IMAGE_ACTUAL_TODAY_DONE_LIST"
TGT_BUILD_IMAGE_ACTUAL_TODAY_DONE_CNT=$(echo "$TGT_BUILD_IMAGE_ACTUAL_DETAILE_TODAY_DONE_LIST" | wc -l)

TGT_BUILD_IMAGE_ACTUAL_NON_TODAY_DONE_LIST="$(echo "$TGT_BUILD_IMAGE_ACTUAL_DETAILE_LIST" | grep -v "$(date "+%Y-%m-%d")")"
TGT_BUILD_IMAGE_ACTUAL_SUMMARY_NON_TODAY_DONE_LIST="$(echo "$TGT_BUILD_IMAGE_ACTUAL_NON_TODAY_DONE_LIST" | cut -d' ' -f1)"
TGT_BUILD_IMAGE_ACTUAL_DETAILE_NON_TODAY_DONE_LIST="$TGT_BUILD_IMAGE_ACTUAL_NON_TODAY_DONE_LIST"
TGT_BUILD_IMAGE_ACTUAL_NON_TODAY_DONE_CNT=$(echo "$TGT_BUILD_IMAGE_ACTUAL_DETAILE_NON_TODAY_DONE_LIST" | wc -l)

TGT_BUILD_IMAGE_NON_DONE_LIST="$(echo "$TGT_BUILD_IMAGE_EXPECT_LIST" | grep -vP "$(echo "$TGT_BUILD_IMAGE_ACTUAL_LIST" | xargs | tr ' ' '|')")"
TGT_BUILD_IMAGE_NON_DONE_CNT=$(echo "$TGT_BUILD_IMAGE_NON_DONE_LIST" |wc -l)

echo "本日のビルド対象予定数は$TGT_BUILD_IMAGE_EXPECT_CNT件でした"
echo "$TGT_BUILD_IMAGE_EXPECT_LIST"
echo "本日のビルド対象実績数は$TGT_BUILD_IMAGE_ACTUAL_CNT件でした"
echo "$TGT_BUILD_IMAGE_ACTUAL_LIST"
echo "ビルド対象実績数の内、日付が本日以内でないものは$TGT_BUILD_IMAGE_ACTUAL_NON_TODAY_DONE_CNT"件でした
echo "$TGT_BUILD_IMAGE_ACTUAL_NON_TODAY_DONE_LIST"
echo "ビルド対象実績数の内、日付が本日以内であるものは$TGT_BUILD_IMAGE_ACTUAL_TODAY_DONE_CNT"件でした
echo "$TGT_BUILD_IMAGE_ACTUAL_TODAY_DONE_LIST"
echo "未作成イメージは$TGT_BUILD_IMAGE_NON_DONE_CNT件でした"
echo "$TGT_BUILD_IMAGE_NON_DONE_LIST"
