#XクライアントがXサーバーにGUI転送出来るように、転送先の「IP:ディスプレイ番号:スクリーン番号」を指定する
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-X.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-nodejs-$NODEJS_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-yarn.sh | bash
