ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=QseDt7167
FROM mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-patch-git-$GIT_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-patch-sqlserver-$SQLSERVER_VERSION.sh | bash
