RUN apt install -y git
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-config-$APP_NAME.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-$APP_NAME-env-usr.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-postgres-$POSTGRES_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-patch-git-$GIT_VERSION.sh | bash
RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list && \
apt update && \
apt upgrade -y
