RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-config-${APP_NAME:-default}.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-healthcheck-${APP_NAME:-default}.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-postgres-$POSTGRES_VERSION.sh | bash
