COPY Komodo-Edit-11.1.1-18206-linux-x86_64.tar.gz /usr/local/src/Komodo-Edit-11.1.1-18206-linux-x86_64.tar.gz
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-komodo-11-1-1.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-php-$PHP_VERSION.sh | bash
