#XクライアントがXサーバーにGUI転送出来るように、転送先の「IP:ディスプレイ番号:スクリーン番号」を指定する
#XクライアントがXサーバーにGUI転送出来るように、転送先の「IP:ディスプレイ番号:スクリーン番号」を指定する
#vscodeインストール
COPY code-1.41.1-1576681965.el7.x86_64.rpm /usr/local/src/code-1.41.1-1576681965.el7.x86_64.rpm
ENV DISPLAY=:0.0
RUN cd /usr/local/src && yum install -y code-1.41.1-1576681965.el7.x86_64.rpm
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-nodejs-$NODEJS_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-yarn.sh | bash
