RUN yum --setopt=tsflags='' reinstall -y man-pages
RUN yum -y install man
RUN yum -y install man-pages-ja.noarch
RUN yum -y install man-pages.noarch
RUN yum groupinstall -y "Input Methods"
RUN yum groupinstall -y base "X Window System" --setopt=group_package_types=mandatory,default,optional
RUN yum install -y PackageKit-gtk3-module
RUN yum install -y ibus-mozc
RUN yum install -y java firefox
RUN yum install -y vlgothic-*
RUN yum install -y xeyes xorg-x11-server-utils xterm xorg-x11-apps
