RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-default-env-usr.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-ghc-8-8-1.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-ghc-haskell-vim-env-usr.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-stack.sh | bash
USER haskell
WORKDIR /home/haskell
