RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-X.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-chromium-$CHROMIUM_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-jdk-$JAVA_VERSION.sh | bash
