RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-apache-http-$APATCH_HTTP_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-post-patch-apache-http-$APATCH_HTTP_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-gron-$GRON_VERSION.sh | bash
