RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-jdk-11.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-elasticsearch-7-5-1.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-kibana-7-5-1.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-config-kibana-7-5-1.sh | bash
