RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-default-env-usr.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-egison-vim-env-usr.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-egison.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-ghc-8-8-1.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-stack.sh | bash
USER egison
WORKDIR /home/egison
