RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-jdk-$JAVA_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-maven-$MAVEN_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-dbeaver-$DBEAVER_VERSION.sh | bash

RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-mariadb-$MARIADB_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-config-mariadb-$MARIADB_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-healthcheck-mariadb-$MARIADB_VERSION.sh | bash
