RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-apache-tomcat-$APACHE_TOMCAT_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-jdk-$JAVA_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-maven-$MAVEN_VERSION.sh | bash
