RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-kdevelop-$KDEVELOP_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-nim-$NIM_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-texinfo-$TEXINFO_VERSION.sh | bash
RUN cd /usr/local/src/$REPO && echo ./$OS_VERSION-install-gdb-$GDB_VERSION.sh | bash
