#Setting up keyboard-configuration (1.191ubuntu3) ...
#Your console font configuration will be updated the next time your system
#boots. If you want to update it now, run 'setupcon' from a virtual console.
#https://qiita.com/munky69rock/items/4c3a076fe496045de5f1
#タイムゾーンの設定（この設定は最初にもってくる。対話入力避けるため。）
#レポジトリを日本サーバーの一つに変更
#日本語環境
